appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CI7HLCaOvm8YfKaRm1hJCkBbrZfsAZzGslOArW4T08fy5bsQdE5zEvCi6XljzZnhomzL7ea3DSPgzGG6j0STyZC/OKUZ0H53YzVi9AiCQyLVWfxd3nSczVuBXPiyg97KlO1gdmQhs04XmycsG98iYyhY4By0S+AcggZ+YzLcrMc4YJRr+8te8UHUBSBWBN8/lDCnN8NCxggv59Lh8ebiFPkbe24mECHCBne9yBisaAAMrAOHoy8X2oJ5/5V5orWBE6PYfqLWpf1L/jWdqCoxTYyjOMSDvVQEF55hcylUjPmbO2l8j2vhwOXo/mtqeJ39K3MW5dSp0VQTllJMuutpZAbOeJbYtfgcx2JYun1SElijWdU0Zo+WOEsR1Z6H8wVam3waQHBACtzPnI16p0QKM0wgMaA012VHJU/5BG8C29j3LpYSP5uzbs8WVQB7zc+1NuIV3b9l9WPbb6yaU6p81msK6HiaAP17cErrgV2ixh0+deBQehdexfZF2SbwMfysI09a02O/8b6TWEAPdIab43A4m5I1Qza0Vl09UH9V1ASuU6OxKFLU0GuzeleQthxeMp+RhrXiI8Lkf22Zwnq/5+p6q3x/KLQ7ntlAKKRRyQqF1KOSNoyoR3DwwN8Pz7bv0Ia25mfbNOMxFO1AaU3wV2yc0TlapYzjD6k6Evp8p5Y=}
conda_forge_output_validation: true
