travis:
  secure:
    BINSTAR_TOKEN: fZrlxOUMi3WjuTDU6CqDalmnj6m8i3+miPS2NkKn3AZIHOJgPFuAUM4uDCbQV6czWuD74ytqXYbBbs5O61IZh+wcmRDPI3X9nFBsIpKIUCHacneDSx6yNWlWdSjc+B0lPJRqrbnOcEfHdbPf2LNCBbJzc+Wp0nKKc/OwqXpLRC5ncD88FTqnXM/19to80m0ZeLqTsZ/0Jh1Wp/u6u7Q463S2vhNv6RPmYF+OItGkXn0glX5J+LYdyGP3chrj/v8m9fKrcwHtbhJetmrcT22LSMPe5dtfr5/A0IeQd6olen3/f+jB734IkZ8Wnxe0znawFKSruyIyjBt/xEQ7P6GY9LgerqTcJbdUwjA35mNrOPO89XHnnPSbQlDOaF1K7YI11dkocT5b7yIDEuj8L1sA5LO924qvfLMARW4V+RVmwGPtJXCK2GC3/zvykh4cn311iDeeAaFHPKjqvR6GHcRfIadn9Bokn44nnt/h9cb46zGoVDFr506V1c9jkb4RvhxWIq+LN80/wV5ICokN9TsDVwtuMVDHqDrG0z9Cwpoh11m+2vpw/lB/rKD9tmY00yi3hMXuTVkAa0MheQcCY89/ZK3Jsawa2u8irpRbITnfYhCR4OSabB8nvn/z+BPDdVXZV5yswd49r8psemp4fR+vWBL3L92GtEefamvoRAKW18o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
